import {
  SiReact,
  SiJavascript,
  SiTypescript,
  SiTailwindcss,
  SiMui,
  SiHtml5,
  SiPython,
  SiRedis,
  SiPhp,
  SiFlask,
  SiLaravel,
  SiPostgresql,
  SiMysql,
  SiSupabase,
  SiPhpmyadmin,
  SiN8N,
  SiGit,
  SiGithub,
  SiBrevo,
  SiDocker,
  SiFilament,
  SiClaudecode,
  SiCursor,
  SiXampp,
  SiJsonwebtokens,
  SiChatwoot,
  SiNodedotjs,
} from 'react-icons/si'

// Mapa único de íconos de tecnologías, reutilizable en proyectos y trayectoria.
export const techIcons = {
  React: SiReact,
  JavaScript: SiJavascript,
  Typescript: SiTypescript,
  'Tailwind CSS': SiTailwindcss,
  'Material UI': SiMui,
  'HTML / CSS': SiHtml5,
  'HTML/CSS': SiHtml5,
  Python: SiPython,
  Redis: SiRedis,
  PHP: SiPhp,
  Flask: SiFlask,
  Laravel: SiLaravel,
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  Supabase: SiSupabase,
  phpMyAdmin: SiPhpmyadmin,
  XAMPP: SiXampp,
  n8n: SiN8N,
  Git: SiGit,
  GitHub: SiGithub,
  Brevo: SiBrevo,
  Docker: SiDocker,
  Filament: SiFilament,
  'Claude Code': SiClaudecode,
  'AI Cursor': SiCursor,
  JWT: SiJsonwebtokens,
  Chatwoot: SiChatwoot,
  'Node.js': SiNodedotjs,
}
